spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:structuralHorizon}
        username: ${POSTGRES_USER:gandalf_the_blue}
        password: ${POSTGRES_PASSWORD:postgres}
    jpa:
        hibernate:
            ddl-auto: create-drop
            show-sql: true
            format-sql: true
            use-sql-comments: true

server:
    address: ${HOST_ADDRESS:localhost}
    port: ${HOST_PORT:8080}
    error:
        include-message: always
    ssl:
        enabled: ${SSL_ENABLED:false}
        key-store-type: PKCS12
        key-store: classpath:keystore.p12
        key-store-password: freevoice
        key-alias: tomcat
