@hostname = {{protocol}}://{{host}}:{{port}}
@contentType = application/json

### register 
# @name newUser
POST {{hostname}}/api/auth/register HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "bucovala@sabina.com",
    "name": "Bucovala Sabina",
    "password": "sab"
}

### login 
# @name user
POST {{hostname}}/api/auth/authenticate HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "seb@cheneb.com",
    "password": "seb"
}

@user-id = {{user.response.body.id}}
@user-email = {{user.response.body.email}}
@user-name = {{user.response.body.name}}
@user-token = {{user.response.body.token}}

### is email available
GET {{hostname}}/api/auth/isEmailAvailable?email={{user-email}} HTTP/1.1
Authorization: Bearer {{user-token}} 

### get name available
GET {{hostname}}/api/auth/isNameAvailable?name={{user-name}} HTTP/1.1
Authorization: Bearer {{user-token}} 